mujoco:
  use_gui: true
  start_paused: false
  fixed: false
  environment: environments/plane.mjcf
  environments_package: ftn_solo

poses:
  zero_pose: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
  initial_pose: [ -0.3, 0.985, -1.57, 0.3, 0.985, -1.57, -0.3, -0.985, 1.57, 0.3, -0.985, 1.57 ]
  upper_pose: [ 0.0, 0.24, -0.45, 0.0, 0.24, -0.45, 0.0, -0.24, 0.45, 0.0, -0.24, 0.45 ]
  fl_up: [ 0.0, 1.2, -2.5, 0.0, 0.485, -0.9, 0.0, -0.485, 0.9, 0.0, -1.2, 2.5 ]
  fr_up: [ 0.0, 0.485, -0.9, 0.0, 1.2, -2.5, 0.0, -1.2, 2.5, 0.0, -0.485, 0.9 ]
  siting: [ 0.0, 0.4, 0.0, 0.0, 0.4, 0.0, 0.0, -1.2, 2.5, 0.0, -1.2, 2.5 ]
on_start:
  poses: [ "initial_pose" ]
  durations: [ 2.0 ]

crawl:
- motions:
  - eef: 18
    position: [ 0.26, -0.14, 0 ]
    orientation: [ 0.0, 0.0, 0.0, 1.0 ] # x, y, z, w
    times: [ 1.0 ]
  duration: 4.0
- motions:
  - eef: 10
    position: [ 0.26, 0.14, 0.0 ]
    orientation: [ 0.0, 0.0, 0.0, 1.0 ] # x, y, z, w
    times: [ 1.0 ]
  duration: 4.0
- motions:
  - eef: 26
    position: [ -0.06, 0.14, 0 ]
    orientation: [ 0.0, 0.0, 0.0, 1.0 ] # x, y, z, w
    times: [ 1.0 ]
  duration: 4.0
- motions:
  - eef: 34
    position: [ -0.06, -0.14, 0 ]
    orientation: [ 0.0, 0.0, 0.0, 1.0 ] # x, y, z, w
    times: [ 1.0 ]
  duration: 4.0
- motions:
  - eef: 10
    position: [ 0.36, 0.14, 0 ]
    orientation: [ 0.0, 0.0, 0.0, 1.0 ] # x, y, z, w
    times: [ 1.0 ]
  duration: 4.0
- motions:
  - eef: 18
    position: [ 0.36, -0.14, 0 ]
    orientation: [ 0.0, 0.0, 0.0, 1.0 ] # x, y, z, w
    times: [ 1.0 ]
  duration: 4.0
- motions:
  - eef: 26
    position: [ 0.04, 0.14, 0 ]
    orientation: [ 0.0, 0.0, 0.0, 1.0 ] # x, y, z, w
    times: [ 1.0 ]
  duration: 4.0
- motions:
  - eef: 34
    position: [ 0.04, -0.14, 0 ]
    orientation: [ 0.0, 0.0, 0.0, 1.0 ] # x, y, z, w
    times: [ 1.0 ]
  duration: 4.0

- motions: []
  duration: 4.0

- motions: []
  duration: 4.0

joint_controller:
  Kp: 5.0
  Kd: 0.05
  B: [ 0.01576374, 0.01089234, 0.03823308,  0.01643371, 0.01248983, 0.00934859, 0.01852457, 0.01234855, 0.00878798, 0.00879661, 0.01211335, 0.00664463 ]
  Fv: [ 0.03963752, 0.10378998, 0.05979448, 0.05197113, 0.11847712, 0.06750289, 0.04130814, 0.07737033, 0.05783389, 0.08236283, 0.06921521, 0.092142 ]
  B: 0.0
  Fv: 0.0
  sigma: [ 0.0125, 0.05, 0.025, 0.05, 0.05, 0.05, 0.0125, 0.05, 0.05, 0.05, 0.05, 0.05 ]
  max_control: 2.2
