mujoco:
  use_gui: true
  start_paused: false
  fixed: false
  environment: environments/plane.mjcf
  environments_package: ftn_solo

poses:
  zero_pose: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
  initial_pose: [ -0.0, 0.985, -1.57, 0.0, 0.985, -1.57, -0.0, 0.985, -1.57, 0.0, 0.985, -1.57 ]
  upper_pose: [ 0.0, 0.24, -0.45, 0.0, 0.24, -0.45, 0.0, -0.24, 0.45, 0.0, -0.24, 0.45 ]
  fl_up: [ 0.0, 1.2, -2.5, 0.0, 0.485, -0.9, 0.0, -0.485, 0.9, 0.0, -1.2, 2.5 ]
  fr_up: [ 0.0, 0.485, -0.9, 0.0, 1.2, -2.5, 0.0, -1.2, 2.5, 0.0, -0.485, 0.9 ]
  siting: [ 0.0, 0.4, 0.0, 0.0, 0.4, 0.0, 0.0, -1.2, 2.5, 0.0, -1.2, 2.5 ]
on_start:
  poses: [ "initial_pose" ]
  durations: [ 2.0 ]

crawl:

- motions:
  - eef: 12
    position: [ 0.36, 0.14, 0.0 ]
    orientation: [ 0.0, 0.0, 0.0, 1.0 ] # x, y, z, w
    times: [ 0.5 ]
  torso_height: 0.3
  duration: 5.0

- motions:
  - eef: 26
    position: [ 0.36, -0.14, 0.0 ]
    orientation: [ 0.0, 0.0, 0.0, 1.0 ] # x, y, z, w
    times: [ 0.5 ]
  duration: 5.0  
  torso_height: 0.3

- motions:
  - eef: 54
    position: [ -0.06, -0.14, 0.0 ]
    orientation: [ 0.0, 0.0, 0.0, 1.0 ] # x, y, z, w
    times: [ 0.5 ]
  duration: 5.0
  torso_height: 0.3

- motions:
  - eef: 40
    position: [ -0.06, 0.14, 0.0 ]
    orientation: [ 0.0, 0.0, 0.0, 1.0 ] # x, y, z, w
    times: [ 0.5 ]
  duration: 5.0
  torso_height: 0.3

- motions:
  - eef: 12
    position: [ 0.56, 0.14, 0.0 ]
    orientation: [ 0.0, 0.0, 0.0, 1.0 ] # x, y, z, w
    times: [ 0.5 ]
  duration: 5.0
  torso_height: 0.3

- motions:
  - eef: 26
    position: [ 0.56, -0.14, 0.0 ]
    orientation: [ 0.0, 0.0, 0.0, 1.0 ] # x, y, z, w
    times: [ 0.5 ]
  duration: 5.0
  torso_height: 0.3

- motions:
  - eef: 54
    position: [ 0.04, -0.14, 0.0 ]
    orientation: [ 0.0, 0.0, 0.0, 1.0 ] # x, y, z, w
    times: [ 0.5 ]
  duration: 5.0
  torso_height: 0.3

- motions:
  - eef: 40
    position: [ 0.04, 0.14, 0.0 ]
    orientation: [ 0.0, 0.0, 0.0, 1.0 ] # x, y, z, w
    times: [ 0.5 ]
  duration: 5.0
  torso_height: 0.3

- motions: []
  duration: 5.0

- motions: []
  duration: 5.0

torso_height: 0.3
max_torque: 23.0

joint_controller:
  Kp: [120.0, 60.0, 60.0, 120.0, 60.0, 60.0, 120.0, 60.0, 60.0, 120.0, 60.0, 60.0]
  Kd: 5
  B: 0.0
  Fv: 0.0
  sigma: 0.05
  max_control: 23.0

whole_body:
  B: 0.0
  Fv: 0.0
  sigma: 0.05
  lambda_tangential: 0.03
  lambda_torque: 0.01
  lambda_kd: 0.01

trajectory_planner:
  COM:
    Kp: 600.5
    Kd: 15.0
  base_linear:
    Kp: 800.0
    Kd: 10.0
  base_angular:
    Kp: 800
    Kd: 20.0