mujoco:
  use_gui: true
  start_paused: false
  fixed: false
  environment: environments/plane.mjcf
  environments_package: ftn_solo

poses:
  zero_pose: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
  initial_pose: [ -0.0, 0.985, -1.57, 0.0, 0.985, -1.57, -0.0, -0.985, 1.57, 0.0, -0.985, 1.57 ]
  upper_pose: [ 0.0, 0.24, -0.45, 0.0, 0.24, -0.45, 0.0, -0.24, 0.45, 0.0, -0.24, 0.45 ]
  fl_up: [ 0.0, 1.2, -2.5, 0.0, 0.485, -0.9, 0.0, -0.485, 0.9, 0.0, -1.2, 2.5 ]
  fr_up: [ 0.0, 0.485, -0.9, 0.0, 1.2, -2.5, 0.0, -1.2, 2.5, 0.0, -0.485, 0.9 ]
  siting: [ 0.0, 0.4, 0.0, 0.0, 0.4, 0.0, 0.0, -1.2, 2.5, 0.0, -1.2, 2.5 ]
on_start:
  poses: [ "initial_pose" ]
  durations: [ 2.0 ]

max_torque: 2.5
crawl:
- motions:
  - eef: 10
    position: [ 0.26, 0.14, 0.0 ]
    orientation: [ 0.0, 0.0, 0.0, 1.0 ] # x, y, z, w
    times: [ 0.5 ]
  duration: 5.0
- motions:
  - eef: 18
    position: [ 0.26, -0.14, 0 ]
    orientation: [ 0.0, 0.0, 0.0, 1.0 ] # x, y, z, w
    times: [ 0.5 ]
  duration: 5.0  

- motions:
  - eef: 34
    position: [ -0.06, -0.14, 0 ]
    orientation: [ 0.0, 0.0, 0.0, 1.0 ] # x, y, z, w
    times: [ 0.5 ]
  duration: 5.0

- motions:
  - eef: 26
    position: [ -0.06, 0.14, 0 ]
    orientation: [ 0.0, 0.0, 0.0, 1.0 ] # x, y, z, w
    times: [ 0.5 ]
  duration: 5.0

- motions:
  - eef: 10
    position: [ 0.36, 0.14, 0 ]
    orientation: [ 0.0, 0.0, 0.0, 1.0 ] # x, y, z, w
    times: [ 0.5 ]
  duration: 5.0
- motions:
  - eef: 18
    position: [ 0.36, -0.14, 0 ]
    orientation: [ 0.0, 0.0, 0.0, 1.0 ] # x, y, z, w
    times: [ 0.5 ]
  duration: 5.0
- motions:
  - eef: 26
    position: [ 0.04, 0.14, 0 ]
    orientation: [ 0.0, 0.0, 0.0, 1.0 ] # x, y, z, w
    times: [ 0.5 ]
  duration: 5.0
- motions:
  - eef: 34
    position: [ 0.04, -0.14, 0 ]
    orientation: [ 0.0, 0.0, 0.0, 1.0 ] # x, y, z, w
    times: [ 0.5 ]
  duration: 5.0

- motions: []
  duration: 5.0

- motions: []
  duration: 5.0

joint_controller:
  Kp: 4.0
  Kd: 0.025
  B: [0.05759784, 0.01348314, 0.04249065, 0.02098579, 0.02374484, 0.01842572, 0.03078875, 0.04640436, 0.01110727, 0.05355997, 0.01646082, 0.01299125]
  Fv: [0.00359281, 0.00565701, 0.00622186, 0.00562885, 0.00414343, 0.0049056, 0.00395552, 0.00468156, 0.0038388 , 0.00642345, 0.00528078, 0.00635379]
  sigma: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]  
  max_control: 2.2

whole_body:
  B: [0.05759784, 0.01348314, 0.04249065, 0.02098579, 0.02374484, 0.01842572, 0.03078875, 0.04640436, 0.01110727, 0.05355997, 0.01646082, 0.01299125]
  Fv: [0.00359281, 0.00565701, 0.00622186, 0.00562885, 0.00414343, 0.0049056, 0.00395552, 0.00468156, 0.0038388 , 0.00642345, 0.00528078, 0.00635379]
  B: 0.0
  Fv: 0.0
  sigma: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]  
  lambda_tangential: 0.03
  lambda_torque: 0.0
  lambda_kd: 0.00