mujoco:
  use_gui: true
  start_paused: false
  fixed: true
  environments_package: ftn_solo

poses:
  zero_pose: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
  initial_pose: [ -0.3, 0.985, -1.57, 0.3, 0.985, -1.57, -0.3, -0.985, 1.57, 0.3, -0.985, 1.57 ]
  upper_pose: [ 0.0, 0.24, -0.45, 0.0, 0.24, -0.45, 0.0, -0.24, 0.45, 0.0, -0.24, 0.45 ]
  fl_up: [ 0.0, 1.2, -2.5, 0.0, 0.485, -0.9, 0.0, -0.485, 0.9, 0.0, -1.2, 2.5 ]
  fr_up: [ 0.0, 0.485, -0.9, 0.0, 1.2, -2.5, 0.0, -1.2, 2.5, 0.0, -0.485, 0.9 ]
  sitting: [ 0.0, 0.4, 0.0, 0.0, 0.4, 0.0, 0.0, -1.2, 2.5, 0.0, -1.2, 2.5 ]
on_start:
  poses: [ "initial_pose" ]
  durations: [ 2.0 ]

cartesian_controller:
  Kp: 0.0
  Kd: 0.01
  B: [0.02855198, 0.01624414, 0.06502044, 0.02913853, 0.02153221, 0.01316274, 0.04364996, 0.0268429 , 0.01043379, 0.02023039, 0.01400522, 0.010488]
  Fv: [0.00352485, 0.00575874, 0.00581546, 0.00350422, 0.00518935, 0.00547, 0.00474679, 0.00821215, 0.00426903, 0.005313, 0.0054171 , 0.00606583]
  sigma: 0.05
  B: 0.0
  Fv: 0.0
  max_control: 2.2


joint_controller:
  Kp: 4.0
  Kd: 0.05
  B: [0.02855198, 0.01624414, 0.06502044, 0.02913853, 0.02153221, 0.01316274, 0.04364996, 0.0268429 , 0.01043379, 0.02023039, 0.01400522, 0.010488]
  Fv: [0.00352485, 0.00575874, 0.00581546, 0.00350422, 0.00518935, 0.00547, 0.00474679, 0.00821215, 0.00426903, 0.005313, 0.0054171 , 0.00606583]
  sigma: 0.05
  B: 0.0
  Fv: 0.0
  max_control: 2.2