mujoco:
  use_gui: true
  start_paused: false
  fixed: true
  # environment: environments/plane.mjcf
  environments_package: ftn_solo

poses:
  zero_pose: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
  initial_pose: [ -0.3, 0.985, -1.57, 0.3, 0.985, -1.57, -0.3, -0.985, 1.57, 0.3, -0.985, 1.57 ]
  upper_pose: [ 0.0, 0.24, -0.45, 0.0, 0.24, -0.45, 0.0, -0.24, 0.45, 0.0, -0.24, 0.45 ]
  fl_up: [ 0.0, 1.2, -2.5, 0.0, 0.485, -0.9, 0.0, -0.485, 0.9, 0.0, -1.2, 2.5 ]
  fr_up: [ 0.0, 0.485, -0.9, 0.0, 1.2, -2.5, 0.0, -1.2, 2.5, 0.0, -0.485, 0.9 ]
  sitting: [ 0.0, 0.4, 0.0, 0.0, 0.4, 0.0, 0.0, -1.2, 2.5, 0.0, -1.2, 2.5 ]
on_start:
  poses: [ "initial_pose" ]
  durations: [ 2.0 ]

cartesian_controller:
  Kp: 0.0
  Kd: 0.01
  B: [0.03657773, 0.02303569, 0.046023, 0.06960387, 0.01832232, 0.01304192, 0.02656115, 0.02520353, 0.01581286, 0.04670965, 0.018501, 0.01430069]
  Fv: [0.00235254, 0.00660975, 0.0051264 , 0.00491761, 0.00708824, 0.00693872, 0.00419985, 0.00598405, 0.00600475, 0.00546261, 0.00670778, 0.00638585]
  sigma: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]  
  max_control: 2.2


joint_controller:
  Kp: 4.0
  Kd: 0.05
  B: [0.03657773, 0.02303569, 0.046023, 0.06960387, 0.01832232, 0.01304192, 0.02656115, 0.02520353, 0.01581286, 0.04670965, 0.018501, 0.01430069]
  Fv: [0.00235254, 0.00660975, 0.0051264 , 0.00491761, 0.00708824, 0.00693872, 0.00419985, 0.00598405, 0.00600475, 0.00546261, 0.00670778, 0.00638585]
  sigma: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]  
  max_control: 2.2
