mujoco:
  use_gui: true
  start_paused: false
  fixed: true
  # environment: environments/plane.mjcf
  environments_package: ftn_solo

poses:
  zero_pose: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
  initial_fl_pose: [ 0.6, 0.985, -1.57, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
  initial_fr_pose: [ 0.0, 0.0, 0.0, -0.6, 0.985, -1.57,  0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
  initial_hl_pose: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.6, -0.985, 1.57, 0.0, 0.0, 0.0,  ]
  initial_hr_pose: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,  -0.6, -0.985, 1.57  ]
  upper_pose: [ 0.0, 0.24, -0.45, 0.0, 0.24, -0.45, 0.0, -0.24, 0.45, 0.0, -0.24, 0.45 ]
  fl_up: [ 0.0, 1.2, -2.5, 0.0, 0.485, -0.9, 0.0, -0.485, 0.9, 0.0, -1.2, 2.5 ]
  fr_up: [ 0.0, 0.485, -0.9, 0.0, 1.2, -2.5, 0.0, -1.2, 2.5, 0.0, -0.485, 0.9 ]
  siting: [ 0.0, 0.4, 0.0, 0.0, 0.4, 0.0, 0.0, -1.2, 2.5, 0.0, -1.2, 2.5 ]
on_start:
  poses: [ "initial_fl_pose" ]
  durations: [ 2.0 ]

loop:
- poses: [ "zero_pose", "initial_fl_pose", "zero_pose", "initial_fl_pose", "zero_pose", "initial_fl_pose" ]
  durations: [ 5.0, 10.0, 15.0, 20.0, 25.0, 30.0 ]
- poses: [ "zero_pose", "initial_fr_pose", "zero_pose", "initial_fr_pose", "zero_pose", "initial_fr_pose" ]
  durations: [ 5.0, 10.0, 15.0, 20.0, 25.0, 30.0 ]
- poses: [ "zero_pose", "initial_hl_pose", "zero_pose", "initial_hl_pose", "zero_pose", "initial_hl_pose" ]
  durations: [ 5.0, 10.0, 15.0, 20.0, 25.0, 30.0 ]
- poses: [ "zero_pose", "initial_hr_pose", "zero_pose", "initial_hr_pose", "zero_pose", "initial_hr_pose" ]
  durations: [ 5.0, 10.0, 15.0, 20.0, 25.0, 30.0 ]
- poses: [ "zero_pose" ]
  durations: [ 5.0 ]

joint_controller:
  Kp: [240.0, 120.0, 120.0, 240.0, 120.0, 120.0, 240.0, 120.0, 120.0, 240.0, 120.0, 120.0]
  Kd: 5
  B: 0.0
  Fv: 0.0
  sigma: 0.05
  max_control: 80.0
