mujoco:
  use_gui: true
  start_paused: false
  fixed: true
  # environment: environments/plane.mjcf
  environments_package: ftn_solo

poses:
  zero_pose: [ 0.0, 0.0, -1.57, 0.0, 0.0, -1.57, 0.0, 0.0, -1.57, 0.0, 0.0, -1.57 ]
  initial_pose: [ -0.3, 0.985, -1.57, 0.3, 0.985, -1.57, -0.3, 0.985, -1.57, 0.3, 0.985, -1.57 ]
  upper_pose: [ 0.0, 0.24, -0.45, 0.0, 0.24, -0.45, 0.0, -0.24, 0.45, 0.0, -0.24, 0.45 ]
  fl_up: [ 0.0, 1.2, -2.5, 0.0, 0.485, -0.9, 0.0, -0.485, 0.9, 0.0, -1.2, 2.5 ]
  fr_up: [ 0.0, 0.485, -0.9, 0.0, 1.2, -2.5, 0.0, -1.2, 2.5, 0.0, -0.485, 0.9 ]
  siting: [ 0.0, 0.4, 0.0, 0.0, 0.4, 0.0, 0.0, -1.2, 2.5, 0.0, -1.2, 2.5 ]
on_start:
  poses: [ "zero_pose" ]
  durations: [ 2.0 ]

loop:
- poses: [  "initial_pose", "zero_pose", "initial_pose", "zero_pose", "initial_pose" ]
  durations: [ 5.0, 10.0, 15.0, 20.0, 25.0]
# - poses: [ "upper_pose" ]
#   durations: [ 5.0 ]


joint_controller:
  Kp: [120.0, 60.0, 60.0, 120.0, 60.0, 60.0, 120.0, 60.0, 60.0, 120.0, 60.0, 60.0]
  Kd: 5.0
  B: [0.04942078, 0.01572849, 0.06912064, 0.04239326, 0.02192039, 0.01842552, 0.03287664, 0.02633164, 0.01044717, 0.03181056, 0.01332392, 0.0117219 ]
  Fv: [0.0031868,  0.00569844, 0.00705093, 0.00238999, 0.00461981, 0.00565022, 0.00374987, 0.0092189,  0.0045631,  0.004821,   0.00551858, 0.00647931]
  sigma: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]
  max_control: 23.7
  B: 0
  Fv: 0
  
