mujoco:
  use_gui: true
  start_paused: false
  fixed: true
  # environment: environments/plane.mjcf
  environments_package: ftn_solo

poses:
  zero_pose: [ 0.0, 0.0, -1.57, 0.0, 0.0, -1.57, 0.0, 0.0, -1.57, 0.0, 0.0, -1.57 ]
  initial_pose: [ -0.3, 0.985, -1.57, 0.3, 0.985, -1.57, -0.3, 0.985, -1.57, 0.3, 0.985, -1.57 ]
  upper_pose: [ 0.0, 0.24, -0.45, 0.0, 0.24, -0.45, 0.0, -0.24, 0.45, 0.0, -0.24, 0.45 ]
  fl_up: [ 0.0, 1.2, -2.5, 0.0, 0.485, -0.9, 0.0, -0.485, 0.9, 0.0, -1.2, 2.5 ]
  fr_up: [ 0.0, 0.485, -0.9, 0.0, 1.2, -2.5, 0.0, -1.2, 2.5, 0.0, -0.485, 0.9 ]
  siting: [ 0.0, 0.4, 0.0, 0.0, 0.4, 0.0, 0.0, -1.2, 2.5, 0.0, -1.2, 2.5 ]
on_start:
  poses: [ "zero_pose" ]
  durations: [ 2.0 ]

loop:
- poses: [  "initial_pose", "zero_pose", "initial_pose", "zero_pose", "initial_pose" ]
  durations: [ 5.0, 10.0, 15.0, 20.0, 25.0]
# - poses: [ "upper_pose" ]
#   durations: [ 5.0 ]


joint_controller:
  Kp: [120.0, 60.0, 60.0, 120.0, 60.0, 60.0, 120.0, 60.0, 60.0, 120.0, 60.0, 60.0]
  Kd: 5.0
  B: [0.02827135, 0.01919119, 0.04705452, 0.02157024, 0.03212002, 0.01155993, 0.02568497, 0.02011642, 0.01542077, 0.04085687, 0.02454722, 0.01154759]
  Fv: [0.00244959, 0.00894722, 0.00555825, 0.00438903, 0.00722227, 0.00758545, 0.00421812, 0.00777405, 0.00518335, 0.00450939, 0.00614908, 0.00974737]
  sigma: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]
  max_control: 23.7
  B: 0
  Fv: 0
  
