mujoco:
  use_gui: true
  start_paused: false
  fixed: false
  environment: environments/big_box.mjcf
  environments_package: ftn_solo

poses:
  zero_pose: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
  initial_pose: [ -0.0, 0.985, -1.57, 0.0, 0.985, -1.57, -0.0, 0.985, -1.57, 0.0, 0.985, -1.57 ]
  upper_pose: [ 0.0, 0.24, -0.45, 0.0, 0.24, -0.45, 0.0, -0.24, 0.45, 0.0, -0.24, 0.45 ]
  fl_up: [ 0.0, 1.2, -2.5, 0.0, 0.485, -0.9, 0.0, -0.485, 0.9, 0.0, -1.2, 2.5 ]
  fr_up: [ 0.0, 0.485, -0.9, 0.0, 1.2, -2.5, 0.0, -1.2, 2.5, 0.0, -0.485, 0.9 ]
  siting: [ 0.0, 0.4, 0.0, 0.0, 0.4, 0.0, 0.0, -1.2, 2.5, 0.0, -1.2, 2.5 ]
on_start:
  poses: [ "initial_pose" ]
  durations: [ 2.0 ]

crawl:
- motions:
  - eef: 12
    position: [0.45, 0.14, 0.15]
    orientation: [0.0,  -0.707, 0,  0.707 ] # x, y, z, w
    times: [0.5]
  duration: 2
  torso_height: 0.3
- motions:
  - eef: 26
    position: [0.45, -0.14, 0.15]
    orientation: [0.0,  -0.707, 0,  0.707 ] # x, y, z, w
    times: [0.5]
  duration: 2
  torso_height: 0.3



- motions:
  - eef: 12
    position: [0.45, 0.14, 0.30]
    orientation: [0.0,  -0.707, 0,  0.707 ] # x, y, z, w
    times: [0.5]
  duration: 2
  torso_height: 0.3
- motions:
  - eef: 26
    position: [0.45, -0.14, 0.30]
    orientation: [0.0,  -0.707, 0,  0.707 ] # x, y, z, w
    times: [0.5]
  duration: 2
  torso_height: 0.3

- motions:
  - eef: 12
    position: [0.45, 0.14, 0.45]
    orientation: [0.0,  -0.707, 0,  0.707 ] # x, y, z, w
    times: [0.5]
  duration: 2
  torso_height: 0.3
- motions:
  - eef: 26
    position: [0.45, -0.14, 0.45]
    orientation: [0.0,  -0.707, 0,  0.707 ] # x, y, z, w
    times: [0.5]
  duration: 2
  torso_height: 0.3  

- motions:
  - eef: 12
    position: [0.45, 0.14, 0.57]
    orientation: [0.0,  -0.707, 0,  0.707 ] # x, y, z, w
    times: [0.5]
  duration: 2
  torso_height: 0.3

- motions:
  - eef: 26
    position: [0.45, -0.14, 0.57]
    orientation: [0.0,  -0.707, 0,  0.707 ] # x, y, z, w
    times: [0.5]
  duration: 2
  torso_height: 0.3  

# - motions:
#   - eef: 12    
#     positions:
#         - [0.38, 0.14, 0.6]
#         - [0.42, 0.14, 0.7]
#         - [0.48, 0.14, 0.62]
#     times: [0.166666, 0.3333, 0.5]
#     orientation: [0.0,  -0.0, 0,  0.1 ] # x, y, z, w
#   duration: 2
#   torso_height: 0.3  

# - motions:
#   - eef: 26
#     positions:
#         - [0.38, -0.14, 0.6]
#         - [0.42, -0.14, 0.7]
#         - [0.48, -0.14, 0.62]
#     times: [0.166666, 0.3333, 0.5]
#     orientation: [0.0,  -0.0, 0,  0.1 ] # x, y, z, w
#   duration: 2
#   torso_height: 0.3  

# - motions:
#   - eef: 54
#     position: [ -0.0, -0.14, 0 ]
#     orientation: [ 0.0, 0.0, 0.0, 1.0 ] # x, y, z, w
#     times: [ 0.5 ]
#   duration: 2.0

# - motions:
#   - eef: 40
#     position: [ -0.0, 0.14, 0 ]
#     orientation: [ 0.0, 0.0, 0.0, 1.0 ] # x, y, z, w
#     times: [ 0.5 ]
#   duration: 2.0  

# - motions:
#   - eef: 12
#     position: [ 0.26, 0.14, 0.0 ]
#     orientation: [ 0.0, 0.0, 0.0, 1.0 ] # x, y, z, w
#     times: [ 0.5 ]
#   duration: 2.0
# - motions:
#   - eef: 26
#     position: [ 0.26, -0.14, 0 ]
#     orientation: [ 0.0, 0.0, 0.0, 1.0 ] # x, y, z, w
#     times: [ 0.5 ]
#   duration: 2.0  



# - motions:
#   - eef: 12
#     position: [ 0.36, 0.14, 0 ]
#     orientation: [ 0.0, 0.0, 0.0, 1.0 ] # x, y, z, w
#     times: [ 0.5 ]
#   duration: 2.0
# - motions:
#   - eef: 26
#     position: [ 0.36, -0.14, 0 ]
#     orientation: [ 0.0, 0.0, 0.0, 1.0 ] # x, y, z, w
#     times: [ 0.5 ]
#   duration: 2.0
# - motions:
#   - eef: 54
#     position: [ 0.04, 0.14, 0 ]
#     orientation: [ 0.0, 0.0, 0.0, 1.0 ] # x, y, z, w
#     times: [ 0.5 ]
#   duration: 2.0
# - motions:
#   - eef: 40
#     position: [ 0.04, -0.14, 0 ]
#     orientation: [ 0.0, 0.0, 0.0, 1.0 ] # x, y, z, w
#     times: [ 0.5 ]
#   duration: 2.0

- motions: []
  duration: 2.0

- motions: []
  duration: 2.0

max_torque: 23.0

joint_controller:
  Kp: [120.0, 60.0, 60.0, 120.0, 60.0, 60.0, 120.0, 60.0, 60.0, 120.0, 60.0, 60.0]
  Kd: 5
  B: [0.03657773, 0.02303569, 0.046023, 0.06960387, 0.01832232, 0.01304192, 0.02656115, 0.02520353, 0.01581286, 0.04670965, 0.018501, 0.01430069]
  Fv: [0.00235254, 0.00660975, 0.0051264 , 0.00491761, 0.00708824, 0.00693872, 0.00419985, 0.00598405, 0.00600475, 0.00546261, 0.00670778, 0.00638585]
  sigma: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]  
  B: 0.0
  Fv: 0.0
  max_control: 23.0

whole_body:
  B: [0.03657773, 0.02303569, 0.046023, 0.06960387, 0.01832232, 0.01304192, 0.02656115, 0.02520353, 0.01581286, 0.04670965, 0.018501, 0.01430069]
  Fv: [0.00235254, 0.00660975, 0.0051264 , 0.00491761, 0.00708824, 0.00693872, 0.00419985, 0.00598405, 0.00600475, 0.00546261, 0.00670778, 0.00638585]
  B: 0.0
  Fv: 0.0
  sigma: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]  
  lambda_tangential: 0.3
  lambda_torque: 0.0
  smooth: 0.95
  # lambda_kd: 0.01