mujoco:
  use_gui: true
  start_paused: false
  fixed: false
  environment: environments/slope_60.mjcf
  environments_package: ftn_solo

poses:
  zero_pose:
    [ 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0,
      0.0, 0.0, 0.0,
      0.0, 0.0, 0.0]
  initial_pose:
    [ 0.0, 0.985, -1.57,
      0.0, 0.985, -1.57,
      0.0, -0.985, 1.57,
      0.0, -0.985, 1.57]
  upper_pose:
    [ 0.0, 0.24, -0.45,
      0.0, 0.24, -0.45,
      0.0, -0.24, 0.45,
      0.0, -0.24, 0.45]
  fl_up:
    [ 0.0, 1.2,   -2.5,
      0.0, 0.485, -0.9,
      0.0, -0.485, 0.9,
      0.0, -1.2,   2.5]
  fr_up:
    [ 0.0, 0.485, -0.9,
      0.0, 1.2,   -2.5,
      0.0, -1.2,   2.5,
      0.0, -0.485, 0.9,]
  siting:
    [ 0.0, 0.4, 0.0,
      0.0, 0.4, 0.0,
      0.0, -1.2, 2.5,
      0.0, -1.2, 2.5]
on_start:
  poses: ["initial_pose"]
  durations: [2.0]

joint_controller:
  Kp: 4.0
  Kd: 0.025
  B: [0.03657773, 0.02303569, 0.046023, 0.06960387, 0.01832232, 0.01304192, 0.02656115, 0.02520353, 0.01581286, 0.04670965, 0.018501, 0.01430069]
  Fv: [0.00235254, 0.00660975, 0.0051264 , 0.00491761, 0.00708824, 0.00693872, 0.00419985, 0.00598405, 0.00600475, 0.00546261, 0.00670778, 0.00638585]
  sigma: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]  
  max_control: 2.2

whole_body:
  B: [0.03657773, 0.02303569, 0.046023, 0.06960387, 0.01832232, 0.01304192, 0.02656115, 0.02520353, 0.01581286, 0.04670965, 0.018501, 0.01430069]
  Fv: [0.00235254, 0.00660975, 0.0051264 , 0.00491761, 0.00708824, 0.00693872, 0.00419985, 0.00598405, 0.00600475, 0.00546261, 0.00670778, 0.00638585]
  B: 0.0
  Fv: 0.0
  sigma: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]  

crawl:
  - motions:
    - eef: 10
      position: [0.26, 0.14, 0.1039]
      orientation: [0.0,  -0.5, 0, 0.866 ] # x, y, z, w
      times: [0.5]
    duration: 2
    torso_height: 0.30

  - motions:
    - eef: 18
      position: [0.26, -0.14, 0.1039]
      orientation: [0.0,  -0.5, 0, 0.866 ] # x, y, z, w
      times: [0.5]
    duration: 2
  - motions:
    - eef: 26
      position: [-0.07, 0.14, 0]
      orientation: [0.0, 0.0, 0.0, 1.0] # x, y, z, w
      times: [0.5]
    duration: 2
  - motions:
    - eef: 34
      position: [-0.07, -0.14, 0]
      orientation: [0.0, 0.0, 0.0, 1.0] # x, y, z, w
      times: [0.5]
    duration: 2

  - motions:
    - eef: 10
      position: [0.32, 0.14, 0.2078]
      orientation: [0.0,  -0.5, 0, 0.866 ] # x, y, z, w
      times: [0.5]
    duration: 2
  - motions:
    - eef: 18
      position: [0.32, -0.14, 0.2078]
      orientation: [0.0,  -0.5, 0, 0.866 ] # x, y, z, w
      times: [0.5]
    duration: 2
  - motions:
    - eef: 26
      position: [0.04, 0.14, 0]
      orientation: [0.0, 0.0, 0.0, 1.0] # x, y, z, w
      times: [0.5]
    duration: 2
  - motions:
    - eef: 34
      position: [0.04, -0.14, 0]
      orientation: [0.0, 0.0, 0.0, 1.0] # x, y, z, w
      times: [0.5]
    duration: 2
  - motions:
    - eef: 26
      position: [0.10, 0.14, 0]
      orientation: [0.0, 0.0, 0.0, 1.0] # x, y, z, w
      times: [0.5]
    duration: 2
  - motions:
    - eef: 34
      position: [0.10, -0.14, 0]
      orientation: [0.0, 0.0, 0.0, 1.0] # x, y, z, w
      times: [0.5]
    duration: 2
  - motions:
    - eef: 10
      position: [0.37, 0.14, 0.294]
      orientation: [0.0,  -0.5, 0, 0.866 ] # x, y, z, w
      times: [0.5]
    duration: 2
  - motions:
    - eef: 18
      position: [0.37, -0.14, 0.294]
      orientation: [0.0,  -0.5, 0, 0.866 ] # x, y, z, w
      times: [0.5]
    duration: 2

  # - motions:
  #   - joints: [8, 11]
  #     position: [-0.7, -0.7]
  #     times: [1]
  #   duration: 2

  - motions:
    - eef: 26
      position: [0.16, 0.14, 0]
      orientation: [0.0, 0.0, 0.0, 1.0] # x, y, z, w
      times: [0.5]
    duration: 2
  - motions:
    - eef: 34
      position: [0.16, -0.14, 0]
      orientation: [0.0, 0.0, 0.0, 1.0] # x, y, z, w
      times: [0.5]
    duration: 2
    torso_height: 0.26


  - motions:
    - eef: 10
      positions:
        - [0.34, 0.14, 0.34]
        - [0.42, 0.14, 0.34]
        - [0.46, 0.14, 0.31]
      times: [0.15, 0.4, 0.5]
      orientation: [0.0, 0.0, 0.0, 1.0] # x, y, z, w
    duration: 2
  - motions:
    - eef: 18
      positions:
        - [0.34, -0.14, 0.34]
        - [0.42, -0.14, 0.34]
        - [0.46, -0.14, 0.31]
      times: [0.15, 0.4, 0.5]
      orientation: [0.0, 0.0, 0.0, 1.0] # x, y, z, w
    duration: 2
  - motions:
    - eef: 26
      position: [0.26, 0.14, 0.1039]
      orientation: [0.0,  -0.5, 0, 0.866 ] # x, y, z, w
      times: [0.5]
    duration: 2

  - motions:
    - eef: 34
      position: [0.26, -0.14, 0.1039]
      orientation: [0.0,  -0.5, 0, 0.866 ] # x, y, z, w
      times: [0.5]
    duration: 2
  - motions:
    - eef: 26
      position: [0.32, 0.14, 0.2078]
      orientation: [0.0,  -0.5, 0, 0.866 ] # x, y, z, w
      times: [0.5]
    duration: 2
  - motions:
    - eef: 10
      position: [0.51, 0.14, 0.31]
      orientation: [0.0, 0.0, 0.0, 1.0] # x, y, z, w
      times: [0.5]
    duration: 2
  - motions:
    - eef: 18
      position: [0.51, -0.14, 0.31]
      orientation: [0.0, 0.0, 0.0, 1.0] # x, y, z, w
      times: [0.5]
    duration: 2
  - motions:
    - eef: 34
      position: [0.32, -0.14, 0.2078]
      orientation: [0.0,  -0.5, 0, 0.866 ] # x, y, z, w
      times: [0.5]
    duration: 2
  - motions:
    - eef: 10
      position: [0.55, 0.14, 0.31]
      orientation: [0.0, 0.0, 0.0, 1.0] # x, y, z, w
      times: [0.5]
    duration: 2
  - motions:
    - eef: 18
      position: [0.55, -0.14, 0.31]
      orientation: [0.0, 0.0, 0.0, 1.0] # x, y, z, w
      times: [0.5]
    duration: 2
  - motions:
    - eef: 10
      position: [0.60, 0.14, 0.31]
      orientation: [0.0, 0.0, 0.0, 1.0] # x, y, z, w
      times: [0.5]
    duration: 2

  - motions:
    - eef: 18
      position: [0.60, -0.14, 0.31]
      orientation: [0.0, 0.0, 0.0, 1.0] # x, y, z, w
      times: [0.5]
    duration: 2
  - motions:
    - eef: 26
      position: [0.37, 0.14, 0.294]
      orientation: [0.0,  -0.5, 0, 0.866 ] # x, y, z, w
      times: [0.5]
    duration: 2
  - motions:
    - eef: 34
      position: [0.37, -0.14, 0.294]
      orientation: [0.0,  -0.5, 0, 0.866 ] # x, y, z, w
      times: [0.5]
    duration: 2





  - motions:
    - eef: 10
      position: [0.70, 0.14, 0.31]
      orientation: [0.0, 0.0, 0.0, 1.0] # x, y, z, w
      times: [0.5]
    duration: 2

  - motions:
    - eef: 18
      position: [0.70, -0.14, 0.31]
      orientation: [0.0, 0.0, 0.0, 1.0] # x, y, z, w

    duration: 2
  - motions:
    - eef: 26
      positions:
        - [0.34, 0.14, 0.34]
        - [0.42, 0.14, 0.34]
        - [0.44, 0.14, 0.31]
      times: [0.15, 0.4, 0.5]
      orientation: [0.0, 0.0, 0.0, 1.0] # x, y, z, w
    duration: 2
  - motions:
    - eef: 34
      positions:
        - [0.34, -0.14, 0.34]
        - [0.42, -0.14, 0.34]
        - [0.44, -0.14, 0.31]
      times: [0.15, 0.4, 0.5]
      orientation: [0.0, 0.0, 0.0, 1.0] # x, y, z, w
    duration: 2
  - motions: []
    duration: 2

  - motions: []
    duration: 2
